### ISSUE TITLE
Issue with file workers after migrating from filesystem to s3

### ISSUE THREAD

**Issue by madsmao** [CollectionFS/Meteor-cfs-s3#33]
I have migrated from using the filesystem for storage to using S3. After having done that, I'm getting the following error when trying to deploy using Meteor UP to a DigitalOcean VPS:

```
Exception in queued task: NoSuchBucket: The specified bucket does not exist
    at Object.Future.wait (/opt/aplusbase/app/programs/server/node_modules/fibers/future.js:326:15)
    at packages/meteor/helpers.js:118
    at Object.self.adapter.remove (packages/cfs:storage-adapter/storageAdapter.server.js:236)
    at packages/cfs:worker/fileWorker.js:62
    at Array.forEach (native)
    at Object._.each._.forEach [as each] (packages/underscore/underscore.js:105)
    at Object.fsCollection.files.find.observe.removed (packages/cfs:worker/fileWorker.js:61)
    at observeChangesCallbacks.removed (packages/minimongo/observe.js:169)
    at self.applyChange.removed (packages/minimongo/observe.js:71)
    at packages/mongo/observe_multiplex.js:163
    - - - - -
    at Request.extractError (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/services/s3.js:235:35)
    at Request.callListeners (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
    at Request.callListeners (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:118:16)
    at Request.callListeners (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:118:16)
    at Request.emit (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:85:10)
    at Request.emitEvent (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/request.js:537:10)
    at Request.emitEvents (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/request.js:511:12)
    at Request.completeRequest (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/request.js:481:10)
    at Request.HTTP_DONE (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/event_listeners.js:235:12)
    at Request.callListeners (/opt/aplusbase/app/programs/server/npm/cfs:s3/node_modules/aws-sdk/lib/sequential_executor.js:117:20)
```

What I would really like to do is avoid the file workers attempting to do anything at all, since no files need uploading to non-existent buckets. I have checked the filesystem for chunks (there are none), and I have also attempted to clean up the database to the best of my ability.

What exactly triggers the file workers to start uploading stuff, and any idea as to how I might find out what non-existent bucket it is they are trying to upload to?

**Comment by aldeed** [comment]
Trying to centralize and close issues. Please post in https://github.com/CollectionFS/Meteor-CollectionFS repo if this is still an issue.
