### ISSUE TITLE
EACCES, permission denied '/var/app/cfs' on AWS beanstalk

### ISSUE THREAD

**Issue by adamgins** [CollectionFS/Meteor-cfs-s3#37]
HI, I am running on AWS Beanstalk and trying to use Demeteorizer to deploy a Meteor 1.0 project (having too many issue with "meteor build"). 

I have my code running on my Mac locally and on a custom AWS build. I am trying to move it to an Elasticbeanstalk deployment.

I replaced cfs-filesystem with cfs-gridfs as per https://github.com/CollectionFS/Meteor-cfs-s3/issues/20

These are the cfs components I have:

```
cfs:graphicsmagick                       0.0.1  Adds `gm` to scope with the ability to perform GraphicsMagick or ImageMagick manipulation
cfs:gridfs                               0.0.0  GridFS storage adapter for CollectionFS
cfs:s3                                   0.0.1  Amazon Web Services S3 storage adapter for CollectionFS
cfs:standard-packages                    0.0.2  Filesystem for Meteor, collectionFS
cfs:ui                                   0.0.0  CollectionFS, provides UI helpers

```

I am getting the following error:

```
/var/log/nodejs/nodejs.log
-------------------------------------

/var/app/current/node_modules/fibers/future.js:173
						throw(ex);
						      ^
Error: EACCES, permission denied '/var/app/cfs'
    at Object.fs.mkdirSync (fs.js:653:18)
    at sync (/var/app/current/node_modules/mkdirp/index.js:55:12)
    at sync (/var/app/current/node_modules/mkdirp/index.js:61:24)
    at Function.sync (/var/app/current/node_modules/mkdirp/index.js:61:24)
    at new FS.Store.FileSystem (packages/cfs:filesystem/filesystem.server.js:37)
    at app/collections/images.js:54:9
    at app/collections/images.js:86:3
    at /var/app/current/programs/server/boot.js:168:10
    at Array.forEach (native)
    at Function._.each._.forEach (/var/app/current/node_modules/underscore/underscore.js:79:11)
=> ImageMagick found
Meteor._wrapAsync has been renamed to Meteor.wrapAsync

```

The only FS file code I am call is with the S3 adapter:

I set this on client and server:
```
FS.HTTP.setBaseUrl('/files');
```

```
Images = new FS.Collection("images", {
    stores: [
        new FS.Store.S3("largeImages", {
           
            accessKeyId: "SOMEACESSKEY", //required if environment variables are not set
            secretAccessKey: "SOMESECRET", //required if environment variables are not set
            bucket: "mybucket", //required
            ACL: "public-read-write", //optional, default is 'private', but you can allow public or secure access routed through your app URL
            beforeWrite: function (fileObj) {
                return {
                    name: 'large_' + fileObj.name()

                };
            },
        
            transformWrite: function(fileObj, readStream, writeStream) {
            
                console.log("creating largerImages:" +  fileObj.name());
                gm(readStream, fileObj.name()).resize('900').autoOrient().stream().pipe(writeStream);
            }
        }),

```
Any ideas, please?

**Comment by aldeed** [comment]
@adamgins, did you figure this out?

**Comment by adamgins** [comment]
@aldeed thanks... kinda... I moved on to AWS opsworks do to another Beanstalk issue.
