### ISSUE TITLE
http.js:731 app crashing with missing s3 image

### ISSUE THREAD

**Issue by justinventuri** [CollectionFS/Meteor-cfs-s3#43]
trying to load an image when it is missing from s3 crashes the app
```
http.js:731
    throw new Error('Can\'t render headers after they are sent to the client.'
          ^
Error: Can't render headers after they are sent to the client.
  at ServerResponse.OutgoingMessage._renderHeaders (http.js:731:11)
  at ServerResponse.writeHead (http.js:1152:20)
  at ProxyServer.<anonymous> (/Users/justinventuri/.meteor/packages/meteor-tool/.1.0.38.19myvjh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/run-proxy.js:96:21)
  at ProxyServer.emit (/Users/justinventuri/.meteor/packages/meteor-tool/.1.0.38.19myvjh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/node_modules/eventemitter3/index.js:100:27)
  at ClientRequest.proxyError (/Users/justinventuri/.meteor/packages/meteor-tool/.1.0.38.19myvjh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:140:16)
  at ClientRequest.emit (events.js:117:20)
  at Socket.socketOnData (http.js:1592:9)
  at TCP.onread (net.js:527:27)
```

**Comment by aldeed** [comment]
Trying to centralize and close issues. Please post in https://github.com/CollectionFS/Meteor-CollectionFS repo if this is still an issue.
